---
title:  "Plotting gene body coverage"
author: "Imad Abugessaisa"
date:   "Jan 12, 2020"
output: html_document
---

```{r echo=FALSE}
options(width=100)
knitr::opts_knit$set(verbose = TRUE)
```

## Perform apoptosis analysis on E_MTAB_2600

```{r load required R libraries}
library(dplyr)
library(Rmisc)
library(ggplot2)
library(knitr)
library(reshape2)
```

Summary
-------
## extract the FPKM table E_MTAB_2600_FPKM_mereged_Apoptosis_genes
The 'E_MTAB_2600_FPKM_mereged_Apoptosis_genes' table was gerangray

``` {r reshap matrix reformat}
E_MTAB_2600Coverage_means_DF_melted  <-  melt(E_MTAB_2600Coverage_means_DF,id=c("Annotation"))

## reanme annoation column values
E_MTAB_2600Coverage_means_DF_melted[1:8690,1] <- "E-MTAB-2600"

```

## Plotting of the mean coveage graph
```{r plotting}
E_MTAB_2600Coverage_means_DF_melted_tgc <-
  summarySE(E_MTAB_2600Coverage_means_DF_melted,measurevar = "value",groupvars =c("Annotation","variable"))
E_MTAB_2600Coverage_means_DF_melted_pd <-
 # position_dodge(0.1) # move them .05 to the left and right
pdf("./E-MTAB-2600_mean_cov.pdf")
 meanPlot <- ggplot(E_MTAB_2600Coverage_means_DF_melted_tgc, aes(x=variable, y=value)) +
  geom_errorbar(aes(ymin=value-ci, ymax=value+ci)) +
  geom_line(aes(group=Annotation)) 
meanPlot =meanPlot+ geom_point(aes(group=1), size=2, shape=21, fill="white") + 
  scale_x_discrete(labels  = c(10, 20,30,40,50,60,70,80,90,100)) + 
  labs(x= "μ of the gene body percentile (5'-> 3')") + 
  labs(y= "Gene coverage")+
  labs(title ="mES | E-MTAB-2600 | SMARTer")
meanPlot =meanPlot+ theme(plot.title = element_text(face = "bold", colour="black", size = 20,margin=margin(0,0,3,0))) 
meanPlot =meanPlot+ theme(axis.ticks = element_line(colour = 'black',size = 1.2,linetype = 'dashed'))
meanPlot =meanPlot+ theme(axis.ticks.length=unit(.2, "cm"))
meanPlot =meanPlot+ theme(axis.title.x = element_text(face="bold", colour="black", size=18,family = "Times")) 
meanPlot =meanPlot+ theme(axis.title.y = element_text(face = "bold", colour="black", size=18,family = "Times"))
meanPlot =meanPlot+ theme(legend.position="none")
meanPlot =meanPlot+ theme(axis.text = element_text(face = "bold", colour="black", size=18)) 
meanPlot =meanPlot+ theme(panel.border  = element_rect(colour = "black",fill = NA,size = 2.2),panel.background = element_rect(fill = NA))
meanPlot =meanPlot+ theme(plot.title = element_text(hjust = 0.5))

meanPlot
dev.off()
```


```{r plot full coverage}
pdf(
  "./E-MTAB-2600_full_cov.pdf")
  x = 1:100
 
   color=rgb(0,0,0,alpha=0.25) 
   par(mai=c(0.82,0.82,0.41,0.12))
    plot(
  x,
  ERR522952,col.axis="black",font.axis=2,
  type = 'l',col= color,
 main = list("mES | E-MTAB-2600 | SMARTer",cex=1.5,col = "black",font=2),
 ylab = list("Gene coverage", col = "black",cex=1.5,font=2),
 xlab = list("Gene body percentile (5'-> 3')", col = "black",cex=1.5,font=2),
 col.main = "blue",cex.lab=3,font.lab=2)
     

lines(x,ERR522996,type='l',col= color)
lines(x,ERR523100,type='l',col= color)
lines(x,ERR522822,type='l',col= color)
lines(x,ERR1211358,type='l',col= color)
lines(x,ERR523097,type='l',col= color)
lines(x,ERR523064,type='l',col= color)
lines(x,ERR522930,type='l',col= color)
lines(x,ERR1211349,type='l',col= color)
lines(x,ERR522921,type='l',col= color)
lines(x,ERR523091,type='l',col= color)
lines(x,ERR1211392,type='l',col= color)
lines(x,ERR522954,type='l',col= color)
lines(x,ERR1211328,type='l',col= color)
lines(x,ERR1211286,type='l',col= color)
lines(x,ERR1211539,type='l',col= color)
lines(x,ERR1211556,type='l',col= color)
lines(x,ERR1211549,type='l',col= color)
lines(x,ERR1211518,type='l',col= color)
lines(x,ERR1211514,type='l',col= color)
lines(x,ERR1211477,type='l',col= color)
lines(x,ERR522953,type='l',col= color)
lines(x,ERR1211345,type='l',col= color)
lines(x,ERR522994,type='l',col= color)
lines(x,ERR1211548,type='l',col= color)
lines(x,ERR1211504,type='l',col= color)
lines(x,ERR1211244,type='l',col= color)
lines(x,ERR1211306,type='l',col= color)
lines(x,ERR1211249,type='l',col= color)
lines(x,ERR522869,type='l',col= color)
lines(x,ERR522967,type='l',col= color)
lines(x,ERR523095,type='l',col= color)
lines(x,ERR1211268,type='l',col= color)
lines(x,ERR522986,type='l',col= color)
lines(x,ERR522843,type='l',col= color)
lines(x,ERR1211234,type='l',col= color)
lines(x,ERR1211260,type='l',col= color)
lines(x,ERR1211276,type='l',col= color)
lines(x,ERR1211261,type='l',col= color)
lines(x,ERR1211178,type='l',col= color)
lines(x,ERR1211272,type='l',col= color)
lines(x,ERR1211466,type='l',col= color)
lines(x,ERR1211238,type='l',col= color)
lines(x,ERR1211256,type='l',col= color)
lines(x,ERR1211210,type='l',col= color)
lines(x,ERR1211243,type='l',col= color)
lines(x,ERR1211475,type='l',col= color)
lines(x,ERR1211199,type='l',col= color)
lines(x,ERR1211202,type='l',col= color)
lines(x,ERR1211225,type='l',col= color)
lines(x,ERR1211189,type='l',col= color)
lines(x,ERR1211209,type='l',col= color)
lines(x,ERR1211242,type='l',col= color)
lines(x,ERR522997,type='l',col= color)
lines(x,ERR1211204,type='l',col= color)
lines(x,ERR1211236,type='l',col= color)
lines(x,ERR1211510,type='l',col= color)
lines(x,ERR1211250,type='l',col= color)
lines(x,ERR1211207,type='l',col= color)
lines(x,ERR1211269,type='l',col= color)
lines(x,ERR1211359,type='l',col= color)
lines(x,ERR523053,type='l',col= color)
lines(x,ERR1211176,type='l',col= color)
lines(x,ERR1211184,type='l',col= color)
lines(x,ERR1211197,type='l',col= color)
lines(x,ERR1211215,type='l',col= color)
lines(x,ERR1211247,type='l',col= color)
lines(x,ERR1211230,type='l',col= color)
lines(x,ERR1211219,type='l',col= color)
lines(x,ERR1211314,type='l',col= color)
lines(x,ERR1211239,type='l',col= color)
lines(x,ERR1211264,type='l',col= color)
lines(x,ERR523181,type='l',col= color)
lines(x,ERR523028,type='l',col= color)
lines(x,ERR1211270,type='l',col= color)
lines(x,ERR1211246,type='l',col= color)
lines(x,ERR1211235,type='l',col= color)
lines(x,ERR523143,type='l',col= color)
lines(x,ERR1211245,type='l',col= color)
lines(x,ERR1211457,type='l',col= color)
lines(x,ERR1211542,type='l',col= color)
lines(x,ERR1211426,type='l',col= color)
lines(x,ERR1211379,type='l',col= color)
lines(x,ERR1211185,type='l',col= color)
lines(x,ERR522820,type='l',col= color)
lines(x,ERR522818,type='l',col= color)
lines(x,ERR1211229,type='l',col= color)
lines(x,ERR1211545,type='l',col= color)
lines(x,ERR1211447,type='l',col= color)
lines(x,ERR1211376,type='l',col= color)
lines(x,ERR1211411,type='l',col= color)
lines(x,ERR1211619,type='l',col= color)
lines(x,ERR1211602,type='l',col= color)
lines(x,ERR1211262,type='l',col= color)
lines(x,ERR1211434,type='l',col= color)
lines(x,ERR1211405,type='l',col= color)
lines(x,ERR1211228,type='l',col= color)
lines(x,ERR1211418,type='l',col= color)
lines(x,ERR1211581,type='l',col= color)
lines(x,ERR1211440,type='l',col= color)
lines(x,ERR1211639,type='l',col= color)
lines(x,ERR1211369,type='l',col= color)
lines(x,ERR1211448,type='l',col= color)
lines(x,ERR1211435,type='l',col= color)
lines(x,ERR1211177,type='l',col= color)
lines(x,ERR1211547,type='l',col= color)
lines(x,ERR1211433,type='l',col= color)
lines(x,ERR1211463,type='l',col= color)
lines(x,ERR1211460,type='l',col= color)
lines(x,ERR1211523,type='l',col= color)
lines(x,ERR1211226,type='l',col= color)
lines(x,ERR1211453,type='l',col= color)
lines(x,ERR1211408,type='l',col= color)
lines(x,ERR1211395,type='l',col= color)
lines(x,ERR1211543,type='l',col= color)
lines(x,ERR1211389,type='l',col= color)
lines(x,ERR1211441,type='l',col= color)
lines(x,ERR1211527,type='l',col= color)
lines(x,ERR1211391,type='l',col= color)
lines(x,ERR1211396,type='l',col= color)
lines(x,ERR1211266,type='l',col= color)
lines(x,ERR1211444,type='l',col= color)
lines(x,ERR1211403,type='l',col= color)
lines(x,ERR1211388,type='l',col= color)
lines(x,ERR1211431,type='l',col= color)
lines(x,ERR1211383,type='l',col= color)
lines(x,ERR1211430,type='l',col= color)
lines(x,ERR1211422,type='l',col= color)
lines(x,ERR1211196,type='l',col= color)
lines(x,ERR1211483,type='l',col= color)
lines(x,ERR1211386,type='l',col= color)
lines(x,ERR1211531,type='l',col= color)
lines(x,ERR1211446,type='l',col= color)
lines(x,ERR1211416,type='l',col= color)
lines(x,ERR1211459,type='l',col= color)
lines(x,ERR1211462,type='l',col= color)
lines(x,ERR1211451,type='l',col= color)
lines(x,ERR1211558,type='l',col= color)
lines(x,ERR1211398,type='l',col= color)
lines(x,ERR1211519,type='l',col= color)
lines(x,ERR1211638,type='l',col= color)
lines(x,ERR1211479,type='l',col= color)
lines(x,ERR1211217,type='l',col= color)
lines(x,ERR1211371,type='l',col= color)
lines(x,ERR1211375,type='l',col= color)
lines(x,ERR1211534,type='l',col= color)
lines(x,ERR1211407,type='l',col= color)
lines(x,ERR1211393,type='l',col= color)
lines(x,ERR1211484,type='l',col= color)
lines(x,ERR1211461,type='l',col= color)
lines(x,ERR1211458,type='l',col= color)
lines(x,ERR1211406,type='l',col= color)
lines(x,ERR1211385,type='l',col= color)
lines(x,ERR1211332,type='l',col= color)
lines(x,ERR1211496,type='l',col= color)
lines(x,ERR1211470,type='l',col= color)
lines(x,ERR1211384,type='l',col= color)
lines(x,ERR1211464,type='l',col= color)
lines(x,ERR522866,type='l',col= color)
lines(x,ERR1211467,type='l',col= color)
lines(x,ERR1211471,type='l',col= color)
lines(x,ERR1211511,type='l',col= color)
lines(x,ERR1211515,type='l',col= color)
lines(x,ERR1211522,type='l',col= color)
lines(x,ERR1211536,type='l',col= color)
lines(x,ERR1211652,type='l',col= color)
lines(x,ERR1211382,type='l',col= color)
lines(x,ERR1211509,type='l',col= color)
lines(x,ERR1211554,type='l',col= color)
lines(x,ERR1211538,type='l',col= color)
lines(x,ERR1211442,type='l',col= color)
lines(x,ERR1211452,type='l',col= color)
lines(x,ERR1211373,type='l',col= color)
lines(x,ERR1211438,type='l',col= color)
lines(x,ERR1211394,type='l',col= color)
lines(x,ERR1211529,type='l',col= color)
lines(x,ERR1211381,type='l',col= color)
lines(x,ERR1211186,type='l',col= color)
lines(x,ERR1211213,type='l',col= color)
lines(x,ERR1211553,type='l',col= color)
lines(x,ERR1211473,type='l',col= color)
lines(x,ERR1211439,type='l',col= color)
lines(x,ERR523093,type='l',col= color)
lines(x,ERR1211232,type='l',col= color)
lines(x,ERR1211436,type='l',col= color)
lines(x,ERR1211364,type='l',col= color)
lines(x,ERR1211397,type='l',col= color)
lines(x,ERR1211319,type='l',col= color)
lines(x,ERR1211476,type='l',col= color)
lines(x,ERR1211485,type='l',col= color)
lines(x,ERR1211402,type='l',col= color)
lines(x,ERR1211449,type='l',col= color)
lines(x,ERR1211559,type='l',col= color)
lines(x,ERR1211181,type='l',col= color)
lines(x,ERR1211507,type='l',col= color)
lines(x,ERR1211241,type='l',col= color)
lines(x,ERR1211456,type='l',col= color)
lines(x,ERR1211481,type='l',col= color)
lines(x,ERR1211489,type='l',col= color)
lines(x,ERR1211537,type='l',col= color)
lines(x,ERR1211413,type='l',col= color)
lines(x,ERR1211220,type='l',col= color)
lines(x,ERR1211506,type='l',col= color)
lines(x,ERR1211499,type='l',col= color)
lines(x,ERR1211454,type='l',col= color)
lines(x,ERR1211469,type='l',col= color)
lines(x,ERR1211401,type='l',col= color)
lines(x,ERR1211505,type='l',col= color)
lines(x,ERR1211387,type='l',col= color)
lines(x,ERR1211427,type='l',col= color)
lines(x,ERR1211303,type='l',col= color)
lines(x,ERR1211508,type='l',col= color)
lines(x,ERR1211399,type='l',col= color)
lines(x,ERR1211201,type='l',col= color)
lines(x,ERR1211552,type='l',col= color)
lines(x,ERR1211429,type='l',col= color)
lines(x,ERR1211378,type='l',col= color)
lines(x,ERR1211455,type='l',col= color)
lines(x,ERR1211257,type='l',col= color)
lines(x,ERR1211551,type='l',col= color)
lines(x,ERR1211535,type='l',col= color)
lines(x,ERR1211390,type='l',col= color)
lines(x,ERR1211432,type='l',col= color)
lines(x,ERR1211258,type='l',col= color)
lines(x,ERR1211374,type='l',col= color)
lines(x,ERR1211252,type='l',col= color)
lines(x,ERR1211419,type='l',col= color)
lines(x,ERR1211528,type='l',col= color)
lines(x,ERR1211513,type='l',col= color)
lines(x,ERR1211248,type='l',col= color)
lines(x,ERR1211421,type='l',col= color)
lines(x,ERR1211412,type='l',col= color)
lines(x,ERR1211530,type='l',col= color)
lines(x,ERR1211231,type='l',col= color)
lines(x,ERR1211524,type='l',col= color)
lines(x,ERR1211372,type='l',col= color)
lines(x,ERR1211532,type='l',col= color)
lines(x,ERR1211415,type='l',col= color)
lines(x,ERR1211502,type='l',col= color)
lines(x,ERR1211492,type='l',col= color)
lines(x,ERR523177,type='l',col= color)
lines(x,ERR1211500,type='l',col= color)
lines(x,ERR1211195,type='l',col= color)
lines(x,ERR1211497,type='l',col= color)
lines(x,ERR1211179,type='l',col= color)
lines(x,ERR1211546,type='l',col= color)
lines(x,ERR1211370,type='l',col= color)
lines(x,ERR1211521,type='l',col= color)
lines(x,ERR1211494,type='l',col= color)
lines(x,ERR1211325,type='l',col= color)
lines(x,ERR1211182,type='l',col= color)
lines(x,ERR1211520,type='l',col= color)
lines(x,ERR1211482,type='l',col= color)
lines(x,ERR1211331,type='l',col= color)
lines(x,ERR1211540,type='l',col= color)
lines(x,ERR1211377,type='l',col= color)
lines(x,ERR1211474,type='l',col= color)
lines(x,ERR1211495,type='l',col= color)
lines(x,ERR1211487,type='l',col= color)
lines(x,ERR1211443,type='l',col= color)
lines(x,ERR1211550,type='l',col= color)
lines(x,ERR1211450,type='l',col= color)
lines(x,ERR1211468,type='l',col= color)
lines(x,ERR523140,type='l',col= color)
lines(x,ERR1211214,type='l',col= color)
lines(x,ERR1211533,type='l',col= color)
lines(x,ERR1211594,type='l',col= color)
lines(x,ERR1211498,type='l',col= color)
lines(x,ERR523107,type='l',col= color)
lines(x,ERR1211445,type='l',col= color)
lines(x,ERR1211425,type='l',col= color)
lines(x,ERR1211282,type='l',col= color)
lines(x,ERR1211650,type='l',col= color)
lines(x,ERR523202,type='l',col= color)
lines(x,ERR1211221,type='l',col= color)
lines(x,ERR522949,type='l',col= color)
lines(x,ERR1211380,type='l',col= color)
lines(x,ERR1211596,type='l',col= color)
lines(x,ERR1211493,type='l',col= color)
lines(x,ERR1211557,type='l',col= color)
lines(x,ERR1211525,type='l',col= color)
lines(x,ERR1211488,type='l',col= color)
lines(x,ERR1211283,type='l',col= color)
lines(x,ERR1211592,type='l',col= color)
lines(x,ERR1211480,type='l',col= color)
lines(x,ERR1211640,type='l',col= color)
lines(x,ERR522985,type='l',col= color)
lines(x,ERR1211255,type='l',col= color)
lines(x,ERR1211350,type='l',col= color)
lines(x,ERR1211648,type='l',col= color)
lines(x,ERR1211490,type='l',col= color)
lines(x,ERR1211183,type='l',col= color)
lines(x,ERR1211188,type='l',col= color)
lines(x,ERR522963,type='l',col= color)
lines(x,ERR1211486,type='l',col= color)
lines(x,ERR1211472,type='l',col= color)
lines(x,ERR1211517,type='l',col= color)
lines(x,ERR523183,type='l',col= color)
lines(x,ERR1211565,type='l',col= color)
lines(x,ERR523114,type='l',col= color)
lines(x,ERR1211334,type='l',col= color)
lines(x,ERR523067,type='l',col= color)
lines(x,ERR523015,type='l',col= color)
lines(x,ERR523162,type='l',col= color)
lines(x,ERR1211410,type='l',col= color)
lines(x,ERR1211424,type='l',col= color)
lines(x,ERR1211633,type='l',col= color)
lines(x,ERR1211609,type='l',col= color)
lines(x,ERR1211212,type='l',col= color)
lines(x,ERR1211512,type='l',col= color)
lines(x,ERR1211437,type='l',col= color)
lines(x,ERR523056,type='l',col= color)
lines(x,ERR523044,type='l',col= color)
lines(x,ERR1211599,type='l',col= color)
lines(x,ERR1211642,type='l',col= color)
lines(x,ERR1211400,type='l',col= color)
lines(x,ERR1211263,type='l',col= color)
lines(x,ERR1211254,type='l',col= color)
lines(x,ERR1211224,type='l',col= color)
lines(x,ERR522928,type='l',col= color)
lines(x,ERR1211544,type='l',col= color)
lines(x,ERR1211645,type='l',col= color)
lines(x,ERR523000,type='l',col= color)
lines(x,ERR1211623,type='l',col= color)
lines(x,ERR523078,type='l',col= color)
lines(x,ERR1211206,type='l',col= color)
lines(x,ERR1211491,type='l',col= color)
lines(x,ERR1211571,type='l',col= color)
lines(x,ERR1211292,type='l',col= color)
lines(x,ERR1211404,type='l',col= color)
lines(x,ERR1211194,type='l',col= color)
lines(x,ERR1211227,type='l',col= color)
lines(x,ERR1211516,type='l',col= color)
lines(x,ERR522831,type='l',col= color)
lines(x,ERR523187,type='l',col= color)
lines(x,ERR1211240,type='l',col= color)
lines(x,ERR523167,type='l',col= color)
lines(x,ERR1211428,type='l',col= color)
lines(x,ERR1211526,type='l',col= color)
lines(x,ERR522852,type='l',col= color)
lines(x,ERR1211205,type='l',col= color)
lines(x,ERR1211465,type='l',col= color)
lines(x,ERR523017,type='l',col= color)
lines(x,ERR522886,type='l',col= color)
lines(x,ERR1211216,type='l',col= color)
lines(x,ERR1211233,type='l',col= color)
lines(x,ERR1211651,type='l',col= color)
lines(x,ERR1211634,type='l',col= color)
lines(x,ERR1211339,type='l',col= color)
lines(x,ERR1211198,type='l',col= color)
lines(x,ERR1211414,type='l',col= color)
lines(x,ERR1211366,type='l',col= color)
lines(x,ERR1211193,type='l',col= color)
lines(x,ERR1211222,type='l',col= color)
lines(x,ERR1211611,type='l',col= color)
lines(x,ERR523186,type='l',col= color)
lines(x,ERR523004,type='l',col= color)
lines(x,ERR1211192,type='l',col= color)
lines(x,ERR522851,type='l',col= color)
lines(x,ERR1211298,type='l',col= color)
lines(x,ERR1211632,type='l',col= color)
lines(x,ERR523039,type='l',col= color)
lines(x,ERR523133,type='l',col= color)
lines(x,ERR1211317,type='l',col= color)
lines(x,ERR1211267,type='l',col= color)
lines(x,ERR1211572,type='l',col= color)
lines(x,ERR1211187,type='l',col= color)
lines(x,ERR523127,type='l',col= color)
lines(x,ERR1211208,type='l',col= color)
lines(x,ERR522889,type='l',col= color)
lines(x,ERR522939,type='l',col= color)
lines(x,ERR1211294,type='l',col= color)
lines(x,ERR1211280,type='l',col= color)
lines(x,ERR522987,type='l',col= color)
lines(x,ERR1211191,type='l',col= color)
lines(x,ERR1211590,type='l',col= color)
lines(x,ERR523045,type='l',col= color)
lines(x,ERR523018,type='l',col= color)
lines(x,ERR522989,type='l',col= color)
lines(x,ERR1211420,type='l',col= color)
lines(x,ERR1211271,type='l',col= color)
lines(x,ERR1211295,type='l',col= color)
lines(x,ERR522990,type='l',col= color)
lines(x,ERR1211289,type='l',col= color)
lines(x,ERR523116,type='l',col= color)
lines(x,ERR523014,type='l',col= color)
lines(x,ERR1211253,type='l',col= color)
lines(x,ERR522966,type='l',col= color)
lines(x,ERR1211333,type='l',col= color)
lines(x,ERR1211190,type='l',col= color)
lines(x,ERR1211423,type='l',col= color)
lines(x,ERR1211200,type='l',col= color)
lines(x,ERR523102,type='l',col= color)
lines(x,ERR1211351,type='l',col= color)
lines(x,ERR1211211,type='l',col= color)
lines(x,ERR1211365,type='l',col= color)
lines(x,ERR522915,type='l',col= color)
lines(x,ERR523151,type='l',col= color)
lines(x,ERR1211501,type='l',col= color)
lines(x,ERR523132,type='l',col= color)
lines(x,ERR523089,type='l',col= color)
lines(x,ERR522938,type='l',col= color)
lines(x,ERR522873,type='l',col= color)
lines(x,ERR522900,type='l',col= color)
lines(x,ERR1211541,type='l',col= color)
lines(x,ERR523013,type='l',col= color)
lines(x,ERR522862,type='l',col= color)
lines(x,ERR523119,type='l',col= color)
lines(x,ERR523050,type='l',col= color)
lines(x,ERR1211561,type='l',col= color)
lines(x,ERR1211251,type='l',col= color)
lines(x,ERR522876,type='l',col= color)
lines(x,ERR1211655,type='l',col= color)
lines(x,ERR1211180,type='l',col= color)
lines(x,ERR523001,type='l',col= color)
lines(x,ERR523179,type='l',col= color)
lines(x,ERR523002,type='l',col= color)
lines(x,ERR1211326,type='l',col= color)
lines(x,ERR1211628,type='l',col= color)
lines(x,ERR1211587,type='l',col= color)
lines(x,ERR523094,type='l',col= color)
lines(x,ERR1211478,type='l',col= color)
lines(x,ERR523155,type='l',col= color)
lines(x,ERR523058,type='l',col= color)
lines(x,ERR523106,type='l',col= color)
lines(x,ERR1211563,type='l',col= color)
lines(x,ERR522838,type='l',col= color)
lines(x,ERR1211604,type='l',col= color)
lines(x,ERR1211615,type='l',col= color)
lines(x,ERR1211593,type='l',col= color)
lines(x,ERR1211329,type='l',col= color)
lines(x,ERR1211368,type='l',col= color)
lines(x,ERR1211625,type='l',col= color)
lines(x,ERR523170,type='l',col= color)
lines(x,ERR1211612,type='l',col= color)
lines(x,ERR522925,type='l',col= color)
lines(x,ERR522908,type='l',col= color)
lines(x,ERR522936,type='l',col= color)
lines(x,ERR523041,type='l',col= color)
lines(x,ERR522840,type='l',col= color)
lines(x,ERR522958,type='l',col= color)
lines(x,ERR1211562,type='l',col= color)
lines(x,ERR1211603,type='l',col= color)
lines(x,ERR523096,type='l',col= color)
lines(x,ERR522841,type='l',col= color)
lines(x,ERR523011,type='l',col= color)
lines(x,ERR1211613,type='l',col= color)
lines(x,ERR1211569,type='l',col= color)
lines(x,ERR522918,type='l',col= color)
lines(x,ERR1211218,type='l',col= color)
lines(x,ERR522962,type='l',col= color)
lines(x,ERR1211637,type='l',col= color)
lines(x,ERR522824,type='l',col= color)
lines(x,ERR1211503,type='l',col= color)
lines(x,ERR1211574,type='l',col= color)
lines(x,ERR523163,type='l',col= color)
lines(x,ERR1211606,type='l',col= color)
lines(x,ERR523036,type='l',col= color)
lines(x,ERR1211576,type='l',col= color)
lines(x,ERR1211582,type='l',col= color)
lines(x,ERR522927,type='l',col= color)
lines(x,ERR1211588,type='l',col= color)
lines(x,ERR1211307,type='l',col= color)
lines(x,ERR1211343,type='l',col= color)
lines(x,ERR523156,type='l',col= color)
lines(x,ERR1211290,type='l',col= color)
lines(x,ERR523077,type='l',col= color)
lines(x,ERR523104,type='l',col= color)
lines(x,ERR522956,type='l',col= color)
lines(x,ERR1211355,type='l',col= color)
lines(x,ERR1211614,type='l',col= color)
lines(x,ERR1211647,type='l',col= color)
lines(x,ERR1211573,type='l',col= color)
lines(x,ERR1211568,type='l',col= color)
lines(x,ERR1211577,type='l',col= color)
lines(x,ERR1211580,type='l',col= color)
lines(x,ERR1211322,type='l',col= color)
lines(x,ERR522837,type='l',col= color)
lines(x,ERR1211567,type='l',col= color)
lines(x,ERR1211302,type='l',col= color)
lines(x,ERR1211636,type='l',col= color)
lines(x,ERR1211304,type='l',col= color)
lines(x,ERR1211631,type='l',col= color)
lines(x,ERR523123,type='l',col= color)
lines(x,ERR523112,type='l',col= color)
lines(x,ERR1211279,type='l',col= color)
lines(x,ERR1211591,type='l',col= color)
lines(x,ERR1211297,type='l',col= color)
lines(x,ERR1211273,type='l',col= color)
lines(x,ERR523141,type='l',col= color)
lines(x,ERR1211293,type='l',col= color)
lines(x,ERR523154,type='l',col= color)
lines(x,ERR523034,type='l',col= color)
lines(x,ERR522919,type='l',col= color)
lines(x,ERR523048,type='l',col= color)
lines(x,ERR1211346,type='l',col= color)
lines(x,ERR522861,type='l',col= color)
lines(x,ERR523012,type='l',col= color)
lines(x,ERR1211635,type='l',col= color)
lines(x,ERR1211223,type='l',col= color)
lines(x,ERR523101,type='l',col= color)
lines(x,ERR523190,type='l',col= color)
lines(x,ERR522898,type='l',col= color)
lines(x,ERR523068,type='l',col= color)
lines(x,ERR523049,type='l',col= color)
lines(x,ERR1211265,type='l',col= color)
lines(x,ERR1211629,type='l',col= color)
lines(x,ERR1211274,type='l',col= color)
lines(x,ERR523057,type='l',col= color)
lines(x,ERR1211203,type='l',col= color)
lines(x,ERR522975,type='l',col= color)
lines(x,ERR1211617,type='l',col= color)
lines(x,ERR522839,type='l',col= color)
lines(x,ERR523003,type='l',col= color)
lines(x,ERR1211575,type='l',col= color)
lines(x,ERR1211278,type='l',col= color)
lines(x,ERR523109,type='l',col= color)
lines(x,ERR1211356,type='l',col= color)
lines(x,ERR523027,type='l',col= color)
lines(x,ERR523108,type='l',col= color)
lines(x,ERR1211323,type='l',col= color)
lines(x,ERR1211605,type='l',col= color)
lines(x,ERR1211564,type='l',col= color)
lines(x,ERR523110,type='l',col= color)
lines(x,ERR522943,type='l',col= color)
lines(x,ERR523199,type='l',col= color)
lines(x,ERR522988,type='l',col= color)
lines(x,ERR1211354,type='l',col= color)
lines(x,ERR523052,type='l',col= color)
lines(x,ERR1211352,type='l',col= color)
lines(x,ERR1211646,type='l',col= color)
lines(x,ERR523032,type='l',col= color)
lines(x,ERR1211618,type='l',col= color)
lines(x,ERR1211653,type='l',col= color)
lines(x,ERR1211300,type='l',col= color)
lines(x,ERR1211589,type='l',col= color)
lines(x,ERR523193,type='l',col= color)
lines(x,ERR522955,type='l',col= color)
lines(x,ERR1211578,type='l',col= color)
lines(x,ERR1211654,type='l',col= color)
lines(x,ERR1211318,type='l',col= color)
lines(x,ERR1211570,type='l',col= color)
lines(x,ERR523201,type='l',col= color)
lines(x,ERR523138,type='l',col= color)
lines(x,ERR523074,type='l',col= color)
lines(x,ERR523197,type='l',col= color)
lines(x,ERR1211607,type='l',col= color)
lines(x,ERR523134,type='l',col= color)
lines(x,ERR522976,type='l',col= color)
lines(x,ERR1211641,type='l',col= color)
lines(x,ERR523182,type='l',col= color)
lines(x,ERR1211630,type='l',col= color)
lines(x,ERR1211597,type='l',col= color)
lines(x,ERR522863,type='l',col= color)
lines(x,ERR522945,type='l',col= color)
lines(x,ERR522877,type='l',col= color)
lines(x,ERR1211644,type='l',col= color)
lines(x,ERR523137,type='l',col= color)
lines(x,ERR1211301,type='l',col= color)
lines(x,ERR522848,type='l',col= color)
lines(x,ERR522957,type='l',col= color)
lines(x,ERR523019,type='l',col= color)
lines(x,ERR522964,type='l',col= color)
lines(x,ERR1211281,type='l',col= color)
lines(x,ERR1211585,type='l',col= color)
lines(x,ERR523055,type='l',col= color)
lines(x,ERR1211417,type='l',col= color)
lines(x,ERR522846,type='l',col= color)
lines(x,ERR1211555,type='l',col= color)
lines(x,ERR522834,type='l',col= color)
lines(x,ERR522887,type='l',col= color)
lines(x,ERR522978,type='l',col= color)
lines(x,ERR1211584,type='l',col= color)
lines(x,ERR523016,type='l',col= color)
lines(x,ERR1211409,type='l',col= color)
lines(x,ERR522981,type='l',col= color)
lines(x,ERR1211622,type='l',col= color)
lines(x,ERR523121,type='l',col= color)
lines(x,ERR523105,type='l',col= color)
lines(x,ERR1211287,type='l',col= color)
lines(x,ERR1211595,type='l',col= color)
lines(x,ERR522856,type='l',col= color)
lines(x,ERR522858,type='l',col= color)
lines(x,ERR522947,type='l',col= color)
lines(x,ERR523098,type='l',col= color)
lines(x,ERR522937,type='l',col= color)
lines(x,ERR1211277,type='l',col= color)
lines(x,ERR1211626,type='l',col= color)
lines(x,ERR523083,type='l',col= color)
lines(x,ERR522882,type='l',col= color)
lines(x,ERR523022,type='l',col= color)
lines(x,ERR1211324,type='l',col= color)
lines(x,ERR522891,type='l',col= color)
lines(x,ERR523128,type='l',col= color)
lines(x,ERR522832,type='l',col= color)
lines(x,ERR523129,type='l',col= color)
lines(x,ERR1211620,type='l',col= color)
lines(x,ERR522971,type='l',col= color)
lines(x,ERR523171,type='l',col= color)
lines(x,ERR523160,type='l',col= color)
lines(x,ERR523042,type='l',col= color)
lines(x,ERR522842,type='l',col= color)
lines(x,ERR522991,type='l',col= color)
lines(x,ERR523191,type='l',col= color)
lines(x,ERR523062,type='l',col= color)
lines(x,ERR523021,type='l',col= color)
lines(x,ERR522932,type='l',col= color)
lines(x,ERR1211566,type='l',col= color)
lines(x,ERR523076,type='l',col= color)
lines(x,ERR522878,type='l',col= color)
lines(x,ERR523087,type='l',col= color)
lines(x,ERR522890,type='l',col= color)
lines(x,ERR523115,type='l',col= color)
lines(x,ERR522933,type='l',col= color)
lines(x,ERR522982,type='l',col= color)
lines(x,ERR523166,type='l',col= color)
lines(x,ERR522845,type='l',col= color)
lines(x,ERR522828,type='l',col= color)
lines(x,ERR522853,type='l',col= color)
lines(x,ERR522998,type='l',col= color)
lines(x,ERR522974,type='l',col= color)
lines(x,ERR522999,type='l',col= color)
lines(x,ERR523020,type='l',col= color)
lines(x,ERR1211237,type='l',col= color)
lines(x,ERR523146,type='l',col= color)
lines(x,ERR1211337,type='l',col= color)
lines(x,ERR523079,type='l',col= color)
lines(x,ERR523040,type='l',col= color)
lines(x,ERR1211610,type='l',col= color)
lines(x,ERR1211313,type='l',col= color)
lines(x,ERR522912,type='l',col= color)
lines(x,ERR523118,type='l',col= color)
lines(x,ERR1211586,type='l',col= color)
lines(x,ERR522894,type='l',col= color)
lines(x,ERR522940,type='l',col= color)
lines(x,ERR522903,type='l',col= color)
lines(x,ERR523038,type='l',col= color)
lines(x,ERR1211327,type='l',col= color)
lines(x,ERR523145,type='l',col= color)
lines(x,ERR1211284,type='l',col= color)
lines(x,ERR1211288,type='l',col= color)
lines(x,ERR1211321,type='l',col= color)
lines(x,ERR522935,type='l',col= color)
lines(x,ERR1211338,type='l',col= color)
lines(x,ERR522970,type='l',col= color)
lines(x,ERR1211311,type='l',col= color)
lines(x,ERR1211627,type='l',col= color)
lines(x,ERR1211320,type='l',col= color)
lines(x,ERR522875,type='l',col= color)
lines(x,ERR523043,type='l',col= color)
lines(x,ERR523125,type='l',col= color)
lines(x,ERR522895,type='l',col= color)
lines(x,ERR523147,type='l',col= color)
lines(x,ERR522959,type='l',col= color)
lines(x,ERR1211649,type='l',col= color)
lines(x,ERR1211259,type='l',col= color)
lines(x,ERR1211608,type='l',col= color)
lines(x,ERR523173,type='l',col= color)
lines(x,ERR522979,type='l',col= color)
lines(x,ERR1211312,type='l',col= color)
lines(x,ERR523071,type='l',col= color)
lines(x,ERR523131,type='l',col= color)
lines(x,ERR1211315,type='l',col= color)
lines(x,ERR522884,type='l',col= color)
lines(x,ERR523030,type='l',col= color)
lines(x,ERR522917,type='l',col= color)
lines(x,ERR523054,type='l',col= color)
lines(x,ERR1211598,type='l',col= color)
lines(x,ERR523172,type='l',col= color)
lines(x,ERR1211624,type='l',col= color)
lines(x,ERR522920,type='l',col= color)
lines(x,ERR522961,type='l',col= color)
lines(x,ERR522897,type='l',col= color)
lines(x,ERR1211275,type='l',col= color)
lines(x,ERR523189,type='l',col= color)
lines(x,ERR522885,type='l',col= color)
lines(x,ERR523025,type='l',col= color)
lines(x,ERR522888,type='l',col= color)
lines(x,ERR1211357,type='l',col= color)
lines(x,ERR523192,type='l',col= color)
lines(x,ERR522924,type='l',col= color)
lines(x,ERR522879,type='l',col= color)
lines(x,ERR523165,type='l',col= color)
lines(x,ERR523051,type='l',col= color)
lines(x,ERR522983,type='l',col= color)
lines(x,ERR523063,type='l',col= color)
lines(x,ERR523158,type='l',col= color)
lines(x,ERR1211344,type='l',col= color)
lines(x,ERR523009,type='l',col= color)
lines(x,ERR522833,type='l',col= color)
lines(x,ERR522880,type='l',col= color)
lines(x,ERR522904,type='l',col= color)
lines(x,ERR523007,type='l',col= color)
lines(x,ERR522881,type='l',col= color)
lines(x,ERR523148,type='l',col= color)
lines(x,ERR1211643,type='l',col= color)
lines(x,ERR1211310,type='l',col= color)
lines(x,ERR522905,type='l',col= color)
lines(x,ERR1211601,type='l',col= color)
lines(x,ERR522942,type='l',col= color)
lines(x,ERR523152,type='l',col= color)
lines(x,ERR523174,type='l',col= color)
lines(x,ERR522972,type='l',col= color)
lines(x,ERR523117,type='l',col= color)
lines(x,ERR522914,type='l',col= color)
lines(x,ERR523047,type='l',col= color)
lines(x,ERR523139,type='l',col= color)
lines(x,ERR523085,type='l',col= color)
lines(x,ERR523072,type='l',col= color)
lines(x,ERR1211309,type='l',col= color)
lines(x,ERR523024,type='l',col= color)
lines(x,ERR1211347,type='l',col= color)
lines(x,ERR523144,type='l',col= color)
lines(x,ERR522899,type='l',col= color)
lines(x,ERR522911,type='l',col= color)
lines(x,ERR522827,type='l',col= color)
lines(x,ERR1211579,type='l',col= color)
lines(x,ERR523065,type='l',col= color)
lines(x,ERR1211583,type='l',col= color)
lines(x,ERR1211316,type='l',col= color)
lines(x,ERR523023,type='l',col= color)
lines(x,ERR1211621,type='l',col= color)
lines(x,ERR1211285,type='l',col= color)
lines(x,ERR1211363,type='l',col= color)
lines(x,ERR522825,type='l',col= color)
lines(x,ERR523157,type='l',col= color)
lines(x,ERR522923,type='l',col= color)
lines(x,ERR522849,type='l',col= color)
lines(x,ERR522909,type='l',col= color)
lines(x,ERR523090,type='l',col= color)
lines(x,ERR523135,type='l',col= color)
lines(x,ERR523136,type='l',col= color)
lines(x,ERR523086,type='l',col= color)
lines(x,ERR522857,type='l',col= color)
lines(x,ERR523069,type='l',col= color)
lines(x,ERR1211335,type='l',col= color)
lines(x,ERR523200,type='l',col= color)
lines(x,ERR522826,type='l',col= color)
lines(x,ERR523195,type='l',col= color)
lines(x,ERR1211616,type='l',col= color)
lines(x,ERR523161,type='l',col= color)
lines(x,ERR1211305,type='l',col= color)
lines(x,ERR523196,type='l',col= color)
lines(x,ERR522860,type='l',col= color)
lines(x,ERR523088,type='l',col= color)
lines(x,ERR523175,type='l',col= color)
lines(x,ERR523169,type='l',col= color)
lines(x,ERR523198,type='l',col= color)
lines(x,ERR1211362,type='l',col= color)
lines(x,ERR1211299,type='l',col= color)
lines(x,ERR1211340,type='l',col= color)
lines(x,ERR522819,type='l',col= color)
lines(x,ERR1211367,type='l',col= color)
lines(x,ERR1211330,type='l',col= color)
lines(x,ERR523099,type='l',col= color)
lines(x,ERR522977,type='l',col= color)
lines(x,ERR523029,type='l',col= color)
lines(x,ERR522968,type='l',col= color)
lines(x,ERR523046,type='l',col= color)
lines(x,ERR1211291,type='l',col= color)
lines(x,ERR523031,type='l',col= color)
lines(x,ERR523066,type='l',col= color)
lines(x,ERR522907,type='l',col= color)
lines(x,ERR523070,type='l',col= color)
lines(x,ERR522941,type='l',col= color)
lines(x,ERR523026,type='l',col= color)
lines(x,ERR522870,type='l',col= color)
lines(x,ERR522864,type='l',col= color)
lines(x,ERR523073,type='l',col= color)
lines(x,ERR1211348,type='l',col= color)
lines(x,ERR522836,type='l',col= color)
lines(x,ERR522871,type='l',col= color)
lines(x,ERR523150,type='l',col= color)
lines(x,ERR523205,type='l',col= color)
lines(x,ERR522916,type='l',col= color)
lines(x,ERR523159,type='l',col= color)
lines(x,ERR522993,type='l',col= color)
lines(x,ERR522867,type='l',col= color)
lines(x,ERR1211308,type='l',col= color)
lines(x,ERR522902,type='l',col= color)
lines(x,ERR523111,type='l',col= color)
lines(x,ERR523149,type='l',col= color)
lines(x,ERR522960,type='l',col= color)
lines(x,ERR523130,type='l',col= color)
lines(x,ERR523194,type='l',col= color)
lines(x,ERR523164,type='l',col= color)
lines(x,ERR523168,type='l',col= color)
lines(x,ERR522847,type='l',col= color)
lines(x,ERR522823,type='l',col= color)
lines(x,ERR523081,type='l',col= color)
lines(x,ERR523010,type='l',col= color)
lines(x,ERR522893,type='l',col= color)
lines(x,ERR522892,type='l',col= color)
lines(x,ERR522931,type='l',col= color)
lines(x,ERR522929,type='l',col= color)
lines(x,ERR522906,type='l',col= color)
lines(x,ERR523120,type='l',col= color)
lines(x,ERR522910,type='l',col= color)
lines(x,ERR1211600,type='l',col= color)
lines(x,ERR523124,type='l',col= color)
lines(x,ERR1211361,type='l',col= color)
lines(x,ERR522969,type='l',col= color)
lines(x,ERR522946,type='l',col= color)
lines(x,ERR522926,type='l',col= color)
lines(x,ERR523103,type='l',col= color)
lines(x,ERR522865,type='l',col= color)
lines(x,ERR1211342,type='l',col= color)
lines(x,ERR522854,type='l',col= color)
lines(x,ERR522901,type='l',col= color)
lines(x,ERR523178,type='l',col= color)
lines(x,ERR523033,type='l',col= color)
lines(x,ERR522973,type='l',col= color)
lines(x,ERR523113,type='l',col= color)
lines(x,ERR522984,type='l',col= color)
lines(x,ERR522992,type='l',col= color)
lines(x,ERR523180,type='l',col= color)
lines(x,ERR522896,type='l',col= color)
lines(x,ERR523084,type='l',col= color)
lines(x,ERR523082,type='l',col= color)
lines(x,ERR522844,type='l',col= color)
lines(x,ERR522830,type='l',col= color)
lines(x,ERR522821,type='l',col= color)
lines(x,ERR522965,type='l',col= color)
lines(x,ERR522980,type='l',col= color)
lines(x,ERR522922,type='l',col= color)
lines(x,ERR523122,type='l',col= color)
lines(x,ERR522948,type='l',col= color)
lines(x,ERR523035,type='l',col= color)
lines(x,ERR522855,type='l',col= color)
lines(x,ERR523184,type='l',col= color)
lines(x,ERR522934,type='l',col= color)
lines(x,ERR523080,type='l',col= color)
lines(x,ERR523126,type='l',col= color)
lines(x,ERR523060,type='l',col= color)
lines(x,ERR522829,type='l',col= color)
lines(x,ERR523153,type='l',col= color)
lines(x,ERR522859,type='l',col= color)
lines(x,ERR523204,type='l',col= color)
lines(x,ERR523006,type='l',col= color)
lines(x,ERR522868,type='l',col= color)
lines(x,ERR523092,type='l',col= color)
lines(x,ERR523005,type='l',col= color)
lines(x,ERR523203,type='l',col= color)
lines(x,ERR1211353,type='l',col= color)
lines(x,ERR522995,type='l',col= color)
lines(x,ERR522883,type='l',col= color)
lines(x,ERR522944,type='l',col= color)
lines(x,ERR1211296,type='l',col= color)
lines(x,ERR522835,type='l',col= color)
lines(x,ERR523059,type='l',col= color)
lines(x,ERR523061,type='l',col= color)
lines(x,ERR1211360,type='l',col= color)
lines(x,ERR1211341,type='l',col= color)
lines(x,ERR523142,type='l',col= color)
lines(x,ERR523037,type='l',col= color)
lines(x,ERR1211336,type='l',col= color)
lines(x,ERR522951,type='l',col= color)
lines(x,ERR522950,type='l',col= color)
lines(x,ERR522874,type='l',col= color)
lines(x,ERR1211560,type='l',col= color)
lines(x,ERR523008,type='l',col= color)
lines(x,ERR523185,type='l',col= color)
lines(x,ERR523206,type='l',col= color)
lines(x,ERR522850,type='l',col= color)
lines(x,ERR523188,type='l',col= color)
lines(x,ERR523075,type='l',col= color)
lines(x,ERR522913,type='l',col= color)
lines(x,ERR522872,type='l',col= color)
lines(x,ERR523176,type='l',col= color)
box(lty = "solid", col = 'black',lwd=3)
axis(side=1,lwd=2,lwd.ticks=4,col.ticks="black")
axis(side=2,lwd=3,lwd.ticks=4,col.ticks="black")
dev.off()
```


dev.off()

```

